### ISSUE TITLE
Crash of f39_downloader.bas compiled to APK in 1.91

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#236]
A user of the BASIC! Android Compiler, J. Jack, notified me by mail that compiling the sample program "**f39_downloader.bas**" creates an APK that crashes immediately (apparently in the command `FTP.OPEN`). Running "f39_downloader.bas" in BASIC! Editor works well.

I could reproduce it as well. This is not a permission issue, the Compiler auto-detects the `android.permission.INTERNET` permission. Even when giving all possible android permissions to the APK, it still crashes.

This is new in 01.91, this did not occur in 01.90.01.

I tried to add traces but my debugging capabilities are reduced: phone non rooted, no access to an emulator.

My study of the `Run.java` code for `FTP.OPEN` did not put anything into light, especially the code to detect the correct use of the `android.permission.INTERNET` permission is the same in Editor mode and in APK mode so it doesn't explain the crash...

**Comment by olimaticer** [comment]
I test it with my test version and it runs fine.

I added
path$="ftp.laughton.com"
**? "ftp Open"**
FTP.OPEN path$, 21, "basic", "basic"
! Clear the default path
path$="/"
loop: % Main loop
**? "ftp dir"**
FTP.DIR prelist
for debugging.

To exclude a device dependent issue here my APK
[f39downloader.zip](https://github.com/RFO-BASIC/Basic/files/932843/f39downloader.zip)

/ Gregor

**Comment by mougino** [comment]
The user has a problem with the official version of BASIC! so I don't see how your post is helping us Gregor...

**Comment by olimaticer** [comment]
I borrowed all Marc's and also your extensions exept something around the RUN command and using getRelativePath.
After carefully testing I did not found the reason why getRelativePath knocked out my test version 
sometimes.
If my test version runs well, so it is implausible that it is a compiler issue, but it is plausible the issue has to do with initializing BASIC!, isApk and/or relative paths.

/ Gregor

**Comment by mougino** [comment]
Some more elements:

The crash only happens with an APK compiled with the **Android Compiler** based on BASIC! v01.91.
The same app compiled with **Quick APK** based on BASIC! v01.91 does not crash.

I put a copy of an Android-Compiler-built APK of "f39_downloader.bas" here:
[http://mougino.free.fr/tmp/f39 downloader.apk](http://mougino.free.fr/tmp/f39%20downloader.apk)

**Comment by mougino** [comment]
User bigshots1995 of the forum bumped this issue. It happens when he's doing a `FTP.OPEN` on his local FTP server.

The only difference in the function `executeFTP_OPEN()` from 1.90 to 1.91 are these 2 lines at the beginning:
```Java
if (!checkPermission("INTERNET"))
  return RunTimeError("Error: INTERNET permissions needed.");
```

These lines (added in 1.91) are shared by a lot of other internet-dependant functions, e.g. `executeGRABURL()`.

I thought I would have the same crash with a simple program like this, but it works well once compiled in APK from the Android Compiler (with the one and only permission "INTERNET"):
```vb
graburl s$,"http://mougino.free.fr"
print s$
do: pause 1: until 0
```

So the problem only comes from these 2 lines **inside** the `executeFTP_OPEN()` function **only**.

Could there be a problem handling a `RunTimeError()` returned by `executeFTP_OPEN()` ? I'm a little lost...

**Comment by mougino** [comment]
I finally managed to grant the READ_LOGS permission to my logcat app and see what's going on:

> java.lang.NoClassDefFoundError: failed resolution of Lorg/apache/commons/net/ftp/FTPClient;
> at com.rfo.ftpdownloader.Run $Interpreter.ftpConnect(Run.java:16083)

I don't know if the "L" in front of org/apache/commons/net/... is the problem.
Anyway I have all the elements to investigate further now.

**Comment by mougino** [comment]
Here we are. The "android.jar" I embed in the Android Compiler seems to be missing the `org.apache.commons.net` class tree...

**Comment by mougino** [comment]
...but I have those classes in a "commons-net-3.0.1.jar" !
So I'll try to add this lib to the "aapt package" command additionally to the "android.jar" include.

**Comment by mougino** [comment]
Nope, doesn't make any sense...

In 1.90 and in 1.91 the lib "commons-net-3.0.1.jar" is always embedded in the libs/ folder of each compiled project... In 1.90 it was correctly linked (FTP.OPEN worked -- or at least I think it did!) but in 1.91 any compiled program using the FTPClient class throws a java.lang.NoClassDefFoundError: failed resolution of Lorg/apache/commons/net/ftp/FTPClient ...

I took the compiled ftpdownloader.apk to my PC, extracted the classes.dex and ran it through dexdump.exe (in the Android Build-Tools) and I can see that the org.apache.commons.net.ftp.FTPClient has a public entry...

I don't know what to do next :(

**Comment by jMarcS** [comment]
What is at Run.java:16083 in the file you build with? In v01.91 it was the closing bracket of the executeFTP method.

Apache Commons Net 3.0.1 is very, very old. Paul put it in the BASIC! source years ago. The current version is 3.6. You could try replacing 3.0.1 with 3.6 and see if it helps.

If you use Android Studio, the jar is not included in the source tree but specified in a build.gradle file.
I have confirmed that Commons Net 3.6 builds, and that it can run GrabURL in a program run from the Editor.

Could the annotations we discussed in GitHub Issue #232 have an effect here?

My development system is in total disarray; I had trouble reconciling Eclipse and Android Studio on the same Linux PC. I think I have it now, but I have several partial change sets to test and commit. I will try to get my act together and help with this topic.

**Comment by mougino** [comment]
My local copy of BASIC! 1.91, for compilation with Android Compiler, has all comments removed to gain some space. Line 16083 of Run.java v1.91 is: `mFTPClient = new FTPClient();` in the `ftpConnect()` method.

I don't use Android Studio nor Eclipse nor ant, gradle etc. I'm using `aapt` in command-line ;-)

I don't think the annotations are concerned here since the Compiler manages to do a full compilation.
It seems to be a problem in the packaging (one of the final steps of a [manual compilation](https://spin.atomicobject.com/2011/08/22/building-android-application-bundles-apks-by-hand/))

I'll try to change the Appache Commons Net to a newer version and tell you how it goes.

**Comment by mougino** [comment]
Same problem with Apache "commons-net-3.6.jar" in the "libs/" project folder.

If I omit commons-net (any version), the compilation stops because it cannot resolve `org.apache.commons.net.ftp.*`

If I include commons-net (any version), the compilation succeeds and the `org.apache.commons.net.ftp.*` appear in the classes.dex. **But** at runtime I still get a

> java.lang.NoClassDefFoundError: failed resolution of Lorg/apache/commons/net/ftp/FTPClient;

**Comment by mougino** [comment]
Perhaps the problem occurs before the packaging... I'm investigating different forms of the "classpath" option[*] for the command line tool `javac` (used for compiling java files to classes)

[*] option to include jar files

**Comment by mougino** [comment]
Some progress: by changing the classpath from "android.jar:libs/commons-net-3.6.jar" to "libs/commons-net-3.6.jar:android.jar", the error changes at runtime (still w/ app crashing)

> ClassLoader referenced unknown path: /data/app/com.rfo.ftpdownloader-1/lib/arm64

I'll continue investigating that trail, it seems the jar is in a wrong path or something ?

**Comment by jMarcS** [comment]
Thanks or the update, Nicolas. I'm disappointed that upgrading commons-net didn't help. I had hoped there was some change in the API that was confusing the compile tools. "Hope" is usually not a valid design specification.

So far I have not found anything to investigate that you have not already written about. Désolé, I don't know enough about the command line tools to be helpful.

To me, the greatest mystery, even greater than `failed resolution of Lorg` (what's that 'L'?), is why it worked in v1.90 and stopped working in v1.91. I will try to investigate that.

One more question: do you see this error only when building on an Android, or also when building on Windows? I think it will be easier for me to learn the process on Windows than on Android!

**Comment by mougino** [comment]
The leading "L" means a returning object, see this [stackoverflow](https://stackoverflow.com/questions/1509943/why-is-an-l-getting-added-to-my-java-path).

The problem only appears when compiling under Android, there is absolutely no problem compiling under Win/Linux.

**Comment by mougino** [comment]
I'm absolutely not sure it worked fine in 1.90.
I actually suspect it never worked fine.
Apache Commons Net is the only jar in the "libs" folder, and only used for its FTP methods. It just happens there was no user compiling an FTP program with the Compiler 1.90...

**Comment by jMarcS** [comment]
- Okay. I built an apk by command-line on Windows and verified that it runs FTP without error. It was a lot of work for you to make the compiler run on Android. I won't try to replicate that work now.
- I've seen that one-letter type indicator in other places in Android, on the boundary between Java and C++. I had not seen it creep into an error message before.
- If v1.90 didn't work either, I won't go that direction. "If it ain't been tested..."
- I'm surprised we're not using more of the commons-net library API. I could try to find another way to get FTP. Not nearly as satisfying as fixing the actual problem, of course.

**Comment by mougino** [comment]
> I'm surprised we're not using more of the commons-net library API. I could try to find another way to get FTP. Not nearly as satisfying as fixing the actual problem, of course.

That's my backup strategy: if nothing works, I'll take the Apache Commons Net' source and copy the java files for the FTP routines to the project **src/** folder, then it should compile fine (we've already got the `android.util.Base64` that way).

**Comment by mougino** [comment]
After hours trying to make classpath/jars work, I had to resolve to using the commons-net FTP source.

I made a zip of all Java files needed for `org.apache.commons.net.*` FTP routines (63 files in 7 folders, based on Apache Commons 3.6), I can send you by mail Marc.

With these Java files in **src/** the Android Compiler manages to compile a full project, and the FTP commands work good. I think this is an acceptable workaround, what do you think?

**Comment by jMarcS** [comment]
Congratulations on your success, Nicolas! Actually, I was thinking of finding a way to do FTP within the current Android API, perhaps using Volley. Your solution is a nice compromise: it solves your problem with no new design work required. Yes, please do send me the files (or a link to a shared folder somewhere).

As for your question, I agree that it's a good workaround, but my reaction was layered:
**_First thought_**: That many files? Worse than I expected; it'll make a real mess of the git repository.
**_Second thought_**: How about if I compile those files into a .jar file and put that in the git repository instead of net-commons-xxx.lib? I did that with a project at work that used a very small piece of a large Apache commons library.
**_Third thought_**: I should not worry about the git repository, for two reasons. **First**, changing from Eclipse to Android Studio requires a different top-level directory structure, which will trash the git repo. **Second**, sometime we must break up Run.java into small files, somewhere between 5 and 300 of them. This has always has been true, and I've been working up to the break-up for years, but it's still a ways off. It's really hard.

So, enough musing. I think that for now my second thought is the correct one. Besides making the repository neater, it eliminates the possibility of somebody in the future messing with the Apache source files. Nothing wrong with messing with the source files, it just makes licensing a little more complicated.

**Comment by jMarcS** [comment]
Afterthought: it may be that your solution may be the only way to succeed using the Apache Commons library. Something about that library is not compatible with the compiler you use on Android. There may be nothing you can do about it, short of asking Apache to change how they build their library.

I recently had a case at work where I compiled some C++ code and a JNI wrapper into a .jar, then made that .jar a dependency of my main project. I had to set the build options correctly when I built the .jar. Otherwise the project would build correctly, but then fail at runtime. Your on-Android build system may have a similar problem with Apache.

**Comment by mougino** [comment]
Closing this issue as it's not a pure RFO BASIC! issue but rather an Android Compiler issue for which I found a workaround.
